import { jsPDF } from "jspdf";

const PAGE_MARGIN_X = 15;
const TOP_MARGIN = 20;
const BOTTOM_MARGIN = 18;
const CONTENT_WIDTH = 180;
const LINE_HEIGHT = 5;

function sanitizeFileName(value) {
  return String(value || "incident")
    .trim()
    .replace(/[<>:"/\\|?*]+/g, "")
    .replace(/\s+/g, "_")
    .toLowerCase();
}

function addPageHeader(doc, title, pageNumber) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(
    "AI Incident Intelligence Platform",
    PAGE_MARGIN_X,
    12
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Incident: ${title}`,
    PAGE_MARGIN_X,
    17
  );

  doc.text(
    `Page ${pageNumber}`,
    pageWidth - PAGE_MARGIN_X,
    12,
    {
      align: "right"
    }
  );

  doc.setDrawColor(210, 220, 235);
  doc.line(
    PAGE_MARGIN_X,
    20,
    pageWidth - PAGE_MARGIN_X,
    20
  );
}

function addPageFooter(doc) {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);

  doc.text(
    "Generated by AI Incident Intelligence Platform",
    pageWidth / 2,
    pageHeight - 8,
    {
      align: "center"
    }
  );

  doc.setTextColor(0, 0, 0);
}

export function exportRunbookPdf(title, runbook) {
  const safeTitle = String(title || "Untitled Incident");
  const safeRunbook =
    String(runbook || "").trim() ||
    "No runbook content is available.";

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let pageNumber = 1;
  let currentY = TOP_MARGIN;

  // First-page title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(
    "AI Incident Intelligence Report",
    pageWidth / 2,
    currentY,
    {
      align: "center"
    }
  );

  currentY += 14;

  doc.setFontSize(14);
  doc.text(
    `Incident: ${safeTitle}`,
    PAGE_MARGIN_X,
    currentY
  );

  currentY += 9;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    PAGE_MARGIN_X,
    currentY
  );

  currentY += 6;

  doc.setDrawColor(180, 190, 205);
  doc.line(
    PAGE_MARGIN_X,
    currentY,
    pageWidth - PAGE_MARGIN_X,
    currentY
  );

  currentY += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Runbook", PAGE_MARGIN_X, currentY);

  currentY += 8;

  doc.setFont("courier", "normal");
  doc.setFontSize(9.5);

  const lines = doc.splitTextToSize(
    safeRunbook,
    CONTENT_WIDTH
  );

  for (const line of lines) {
    const maximumY = pageHeight - BOTTOM_MARGIN;

    if (currentY + LINE_HEIGHT > maximumY) {
      addPageFooter(doc);

      doc.addPage();
      pageNumber += 1;

      addPageHeader(
        doc,
        safeTitle,
        pageNumber
      );

      doc.setFont("courier", "normal");
      doc.setFontSize(9.5);

      currentY = 28;
    }

    doc.text(
      String(line),
      PAGE_MARGIN_X,
      currentY
    );

    currentY += LINE_HEIGHT;
  }

  addPageFooter(doc);

  const fileName =
    `${sanitizeFileName(safeTitle)}_runbook.pdf`;

  doc.save(fileName);
}